title: Moj awesome title
author: Mark097
email: jmarkisa97@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Ovo je moj awesome description koji bas i ne radi nista ali 
  eto tu je jer mi treba jedan paragraf minimum pa eto.

# social links
twitter_username: markonime # DO NOT include the @ character, or else the build will fail!
github_username:  Mark097 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
